src/Entity/PurchasedProduct.php
<?php

namespace App\Entity;

use App\Repository\PurchasedProductRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PurchasedProductRepository::class)]
class PurchasedProduct
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'purchasedProducts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Order $order_id = null;

    #[ORM\ManyToOne(inversedBy: 'purchasedProducts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Product $product_id = null;

    #[ORM\Column]
    private ?int $quantity = null;

    #[ORM\Column]
    private ?float $unit_price = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOrderId(): ?Order
    {
        return $this->order_id;
    }

    public function setOrderId(?Order $order_id): self
    {
        $this->order_id = $order_id;

        return $this;
    }

    public function getProductId(): ?Product
    {
        return $this->product_id;
    }

    public function setProductId(?Product $product_id): self
    {
        $this->product_id = $product_id;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getUnitPrice(): ?float
    {
        return $this->unit_price;
    }

    public function setUnitPrice(float $unit_price): self
    {
        $this->unit_price = $unit_price;

        return $this;
    }
}

src/Form/PurchasedProductType.php
<?php

namespace App\Form;

use App\Entity\PurchasedProduct;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PurchasedProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('quantity')
            ->add('unit_price')
            ->add('order_id')
            ->add('product_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => PurchasedProduct::class,
        ]);
    }
}

src/Controller/PurchasedProductController.php
<?php

namespace App\Controller;

use App\Entity\PurchasedProduct;
use App\Form\PurchasedProductType;
use App\Repository\PurchasedProductRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/purchased/product')]
class PurchasedProductController extends AbstractController
{
    #[Route('/', name: 'app_purchased_product_index', methods: ['GET'])]
    public function index(PurchasedProductRepository $purchasedProductRepository): Response
    {
        return $this->render('purchased_product/index.html.twig', [
            'purchased_products' => $purchasedProductRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_purchased_product_new', methods: ['GET', 'POST'])]
    public function new(Request $request, PurchasedProductRepository $purchasedProductRepository): Response
    {
        $purchasedProduct = new PurchasedProduct();
        $form = $this->createForm(PurchasedProductType::class, $purchasedProduct);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $purchasedProductRepository->save($purchasedProduct, true);

            return $this->redirectToRoute('app_purchased_product_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('purchased_product/new.html.twig', [
            'purchased_product' => $purchasedProduct,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_purchased_product_show', methods: ['GET'])]
    public function show(PurchasedProduct $purchasedProduct): Response
    {
        return $this->render('purchased_product/show.html.twig', [
            'purchased_product' => $purchasedProduct,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_purchased_product_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, PurchasedProduct $purchasedProduct, PurchasedProductRepository $purchasedProductRepository): Response
    {
        $form = $this->createForm(PurchasedProductType::class, $purchasedProduct);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $purchasedProductRepository->save($purchasedProduct, true);

            return $this->redirectToRoute('app_purchased_product_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('purchased_product/edit.html.twig', [
            'purchased_product' => $purchasedProduct,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_purchased_product_delete', methods: ['POST'])]
    public function delete(Request $request, PurchasedProduct $purchasedProduct, PurchasedProductRepository $purchasedProductRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$purchasedProduct->getId(), $request->request->get('_token'))) {
            $purchasedProductRepository->remove($purchasedProduct, true);
        }

        return $this->redirectToRoute('app_purchased_product_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/purchased_product/_delete_form.html.twig
<form method="post" action="{{ path('app_purchased_product_delete', {'id': purchased_product.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ purchased_product.id) }}">
    <button class="btn">Delete</button>
</form>

templates/purchased_product/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/purchased_product/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit PurchasedProduct{% endblock %}

{% block body %}
    <h1>Edit PurchasedProduct</h1>

    {{ include('purchased_product/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_purchased_product_index') }}">back to list</a>

    {{ include('purchased_product/_delete_form.html.twig') }}
{% endblock %}

templates/purchased_product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}PurchasedProduct index{% endblock %}

{% block body %}
    <h1>PurchasedProduct index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Quantity</th>
                <th>Unit_price</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for purchased_product in purchased_products %}
            <tr>
                <td>{{ purchased_product.id }}</td>
                <td>{{ purchased_product.quantity }}</td>
                <td>{{ purchased_product.unitPrice }}</td>
                <td>
                    <a href="{{ path('app_purchased_product_show', {'id': purchased_product.id}) }}">show</a>
                    <a href="{{ path('app_purchased_product_edit', {'id': purchased_product.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_purchased_product_new') }}">Create new</a>
{% endblock %}

templates/purchased_product/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New PurchasedProduct{% endblock %}

{% block body %}
    <h1>Create new PurchasedProduct</h1>

    {{ include('purchased_product/_form.html.twig') }}

    <a href="{{ path('app_purchased_product_index') }}">back to list</a>
{% endblock %}

templates/purchased_product/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}PurchasedProduct{% endblock %}

{% block body %}
    <h1>PurchasedProduct</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ purchased_product.id }}</td>
            </tr>
            <tr>
                <th>Quantity</th>
                <td>{{ purchased_product.quantity }}</td>
            </tr>
            <tr>
                <th>Unit_price</th>
                <td>{{ purchased_product.unitPrice }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_purchased_product_index') }}">back to list</a>

    <a href="{{ path('app_purchased_product_edit', {'id': purchased_product.id}) }}">edit</a>

    {{ include('purchased_product/_delete_form.html.twig') }}
{% endblock %}